# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "banana")
Ingredient.create(name: "ice cubes")
Ingredient.create(name: "mango leaves")
Ingredient.create(name: "orange")
Ingredient.create(name: "blue ice")
Ingredient.create(name: "russian vodka")
Ingredient.create(name: "fruta do conde")
Ingredient.create(name: "coke")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "abacaxi")
Ingredient.create(name: "orange fanta")
Ingredient.create(name: "american beer")
Ingredient.create(name: "uva")
Ingredient.create(name: "milk")
Ingredient.create(name: "IPA beer")
Ingredient.create(name: "água em gás")
Ingredient.create(name: "vodka")
Ingredient.create(name: "cascalho")
Ingredient.create(name: "plástico")
Ingredient.create(name: "cacos de vidro")
